nick: chat_demo
networks:
  freenode:
    host: chat.freenode.net
    port: 6667
    channels:
      # Channel names does not need to have "#" prefix
      - jabbot
      - test

      # If they do, they are read as-is, and then you need to quote it
      # - "#ubunto"
      # - "##linux"
      # - "##c"

      # Channel with key are given as an array ref
      # - [secret_channnel, k3y0fch4n ]
