
twitter:
  username: my_twitter_account
  password: s0m3th1n6


## Plurk config. All three top-level keys are optional.
## Uncomment the following block and put the correct values there to enable plurk support.

#
# plurk:
#   username: my_plurk_account
#   password: s0m3th1n6

irc:
  nick: chat_demo
  networks:
    freenode:
      host: chat.freenode.net
      port: 6667
      channels:
        # Channel names does not need to have "#" prefix
        - jabbot
        # - test

        # If they do, they are read as-is, and then you need to quote it
        # - "#ubunto"
        # - "##linux"
        # - "##c"

        # Channel with key are given as an array ref
        # - [secret_channnel, k3y0fch4n ]
